# Generated by Django 5.2.3 on 2025-06-10 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regimen', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Régimen',
                'verbose_name_plural': 'Tipos de Régimen',
                'db_table': 'tipo_regimen',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('url_bolsa_trabajo', models.URLField(blank=True, max_length=500, null=True)),
                ('correo_contacto', models.EmailField(max_length=100)),
                ('logo_empresa', models.FileField(blank=True, null=True, upload_to='logos_empresas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('carta_compromiso', models.FileField(blank=True, null=True, upload_to='cartas_compromiso/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('correo_administrador', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajos.tiporegimen')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CURP debe tener el formato correcto', regex='^[A-Z]{4}[0-9]{6}[HM][A-Z]{5}[0-9A-Z]{2}$')])),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe tener entre 9 y 15 dígitos', regex='^\\+?1?\\d{9,15}$')])),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel_academico', models.CharField(blank=True, choices=[('Sin estudios', 'Sin estudios'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Técnico', 'Técnico'), ('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
                ('documento_identificacion', models.FileField(blank=True, null=True, upload_to='documentos_usuarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('curriculum_vitae', models.FileField(blank=True, null=True, upload_to='curriculum/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'usuario_perfil',
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacante', models.CharField(max_length=200)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_expiracion', models.DateField()),
                ('area_desempeno', models.CharField(blank=True, max_length=150)),
                ('descripcion_actividades', models.TextField(blank=True)),
                ('edad_min', models.IntegerField(blank=True, null=True)),
                ('edad_max', models.IntegerField(blank=True, null=True)),
                ('titulo_requerido', models.CharField(blank=True, max_length=200)),
                ('tipo_vacante', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Por proyecto', 'Por proyecto'), ('Temporal', 'Temporal'), ('Prácticas', 'Prácticas')], default='Tiempo completo', max_length=20)),
                ('delegacion', models.CharField(blank=True, max_length=100)),
                ('nivel_academico', models.CharField(blank=True, choices=[('Sin estudios', 'Sin estudios'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Técnico', 'Técnico'), ('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('Unión libre', 'Unión libre'), ('Indistinto', 'Indistinto')], default='Indistinto', max_length=15)),
                ('personas_discapacidad', models.BooleanField(default=False)),
                ('adultos_mayores', models.BooleanField(default=False)),
                ('vacante_mujer', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.empresa')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'db_table': 'vacantes',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_empresas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.documentos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.empresa')),
            ],
            options={
                'verbose_name': 'Documento de Empresa',
                'verbose_name_plural': 'Documentos de Empresas',
                'db_table': 'empresa_documentos',
                'unique_together': {('empresa', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='RegimenDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.documentos')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.tiporegimen')),
            ],
            options={
                'verbose_name': 'Documento por Régimen',
                'verbose_name_plural': 'Documentos por Régimen',
                'db_table': 'regimen_documentos',
                'unique_together': {('regimen', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revisión', 'En revisión'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.vacante')),
            ],
            options={
                'verbose_name': 'Aplicación a Vacante',
                'verbose_name_plural': 'Aplicaciones a Vacantes',
                'db_table': 'usuario_vacante',
                'ordering': ['-fecha_aplicacion'],
                'unique_together': {('usuario', 'vacante')},
            },
        ),
    ]
